### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by danielaciuperca** [cul1n/E-Ticketing-Platform#1]
1. Should be private.
https://github.com/cul1n/E-Ticketing-Platform/blob/fe366664c04162a78a217115b80bebc84b70c876/src/model/Event.java#L7
2. Are you using this?
https://github.com/cul1n/E-Ticketing-Platform/blob/fe366664c04162a78a217115b80bebc84b70c876/src/model/Location.java#L3
3. This is automatically initialized with 0, as it's a field. No need to set it here.
https://github.com/cul1n/E-Ticketing-Platform/blob/fe366664c04162a78a217115b80bebc84b70c876/src/model/User.java#L19
4. Variables hsould have significant name. u should be something similar to user.
https://github.com/cul1n/E-Ticketing-Platform/blob/fe366664c04162a78a217115b80bebc84b70c876/src/service/UserService.java#L14

**Comment by cul1n** [comment]
1. Made field private.
2. Removed unused import.
3. Removed unnecessary initialization.
4. Changed names of variables from u to user.

(4997b2bd174ab5721bbd7894ff737d793f4fcdbf)
